#  -1- Merge the training and the test sets to create one data set. (10299 obs. of 563 var.)
activityFile <- read.table("activity_labels.txt")
featuresFile <- read.table("features.txt")
testData <- read.table("test/X_test.txt")
subjectTestData <- read.table("test/subject_test.txt")
testActivity <- read.table("test/y_test.txt")
combinedTestData <- cbind(testActivity, subjectTestData, testData)
trainData <- read.table("train/X_train.txt")
subjectTrainData <- read.table("train/subject_train.txt")
trainActivity <- read.table("train/y_train.txt")
combinedTrainData <- cbind(trainActivity, subjectTrainData, trainData)
testAndTrainData <- rbind(combinedTestData, combinedTrainData)
#  -2- Extracts only the measurements on the mean and standard deviation for each measurement. (10299 obs. of 68 var.)
newColumnNames <- c("Activity", "Subject", make.names(featuresFile[,2],unique=TRUE))
colnames(testAndTrainData) <- newColumnNames
shrinkFileActivity <- select(testAndTrainData,contains("Activity"))
shrinkFileSubject <- select(testAndTrainData,contains("Subject"))
shrinkFileMean <- select(testAndTrainData,contains(".Mean."))
shrinkFileSD <- select(testAndTrainData,contains(".std."))
reducedFile <- cbind(shrinkFileActivity, shrinkFileSubject, shrinkFileMean, shrinkFileSD)
#  -3- Uses descriptive activity names to name the activities in the data set.  (10299 obs. of 68 var.)
reducedFile$Activity <- factor(reducedFile$Activity, labels = c("WALKING", "WALKING_UPSTAIRS", "WALKING_DOWNSTAIRS", "SITTING", "STANDING", "LAYING")) 
#  -4- Labels the data set with descriptive variable names. (10299 obs. of 68 var.)
descriptiveColumnNames <- c("Activity", "Subject", "TimeBodyAccMeanXaxis", "TimeBodyAccMeanYaxis", "TimeBodyAccMeanZaxis", "TimeGravityAccMeanXaxis", "TimeGravityAccMeanYaxis", "TimeGravityAccMeanZaxis", "TimeBodyAccJerkMeanXaxis", "TimeBodyAccJerkMeanYaxis", "TimeBodyAccJerkMeanZaxis", "TimeBodyGyroMeanXaxis", "TimeBodyGyroMeanYaxis", "TimeBodyGyroMeanZaxis", "TimeBodyGyroJerkMeanXaxis", "TimeBodyGyroJerkMeanYaxis", "TimeBodyGyroJerkMeanZaxis", "TimeBodyAccMagMean", "TimeGravityAccMagMean", "TimeBodyAccJerkMagMean", "TimeBodyGyroMagMean", "TimeBodyGyroJerkMagMean", "FastBodyAccMeanXaxis", "FastBodyAccMeanYaxis", "FastBodyAccMeanZaxis", "FastBodyAccJerkMeanXaxis", "FastBodyAccJerkMeanYaxis", "FastBodyAccJerkMeanZaxis", "FastBodyGyroMeanXaxis", "FastBodyGyroMeanYaxis", "FastBodyGyroMeanZaxis", "FastBodyAccMagMean", "FastBodyAccJerkMagMean", "FastBodyGyroMagMean", "FastBodyGyroJerkMagMean", "TimeBodyAccStdXaxis", "TimeBodyAccStdYaxis", "TimeBodyAccStdZaxis", "TimeGravityAccStdXaxis", "TimeGravityAccStdYaxis", "TimeGravityAccStdZaxis", "TimeBodyAccJerkStdXaxis", "TimeBodyAccJerkStdYaxis", "TimeBodyAccJerkStdZaxis", "TimeBodyGyroStdXaxis", "TimeBodyGyroStdYaxis", "TimeBodyGyroStdZaxis", "TimeBodyGyroJerkStdXaxis", "TimeBodyGyroJerkStdYaxis", "TimeBodyGyroJerkStdZaxis", "TimeBodyAccMagStd", "TimeGravityAccMagStd", "TimeBodyAccJerkMagStd", "TimeBodyGyroMagStd", "TimeBodyGyroJerkMagStd", "FastBodyAccStdXaxis", "FastBodyAccStdYaxis", "FastBodyAccStdZaxis", "FastBodyAccJerkStdXaxis", "FastBodyAccJerkStdYaxis", "FastBodyAccJerkStdZaxis", "FastBodyGyroStdXaxis", "FastBodyGyroStdYaxis", "FastBodyGyroStdZaxis", "FastBodyAccMagStd", "FastBodyAccJerkMagStd", "FastBodyGyroMagStd", "FastBodyGyroJerkMagStd")
colnames(reducedFile) <- descriptiveColumnNames
#  -5- Creates an independent tidy data set with the average of each variable for each activity and each subject. (180 obs. of 68 vars.) 
finalGrouping <-data.table(reducedFile %>%
              group_by(Subject,Activity) %>%
              summarise_each(funs(mean)))
write.table(finalGrouping, "C:/R/R Programming/Getting_and_Cleaning_Data/UCI HAR Dataset/finalGrouping.txt", row.name=FALSE) 